name: Update Contest Results

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ main, feature/progress-tracker ]
  schedule:
  - cron: "0 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Scrape the GitHub API 
      run: |
        pip install -r _data/requirements.txt
        python _data/scrape_github.py
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Deploy to GitHub Pages
      uses: joshlarsen/jekyll4-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        PAGES_REPO_NWO: ${{ secrets.GITHUB_REPOSITORY }}
