name: Update Contest Results

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ main, feature/progress-tracker ]
  schedule:
  - cron: "0 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Setup Ruby 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Scrape the GitHub API 
      run: |
        pip install -r _data/requirements.txt
        python _data/scrape_github.py
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the website 
      run:  bundle exec jekyll build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        PUBLISH_DIR: _site 
        PUBLISH_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
